import { Inter } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/context/SidebarContext";
import Sidebar from "@/components/sidebar/index";
import Navbar from "@/components/navbar/Navbar";
// import Navigation from "@/components/Navigation";
import Footer from "@/components/footer/Footer";
// import UserContextProvider from "@/context/UserContext.jsx";
import { UserProvider } from "@/context/userContext";
import AuthProvider from "@/context/auth";
import { BasketProvider } from "@/context/BasketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="relative">
      <div className="flex">
        <Sidebar />
        <div className="w-full h-screen px-24">{children}</div>
      </div>
    </div>
  );
}
